# Generated by Django 3.2.12 on 2022-02-17 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userotp_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOtp',
            new_name='EmailOtp',
        ),
        migrations.RenameField(
            model_name='emailotp',
            old_name='user_otp',
            new_name='otp_user_email',
        ),
        migrations.CreateModel(
            name='MobileOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(help_text="User's OTP.", max_length=5)),
                ('otp_user_mobile', models.OneToOneField(help_text='User.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
